#!/bin/sh

echo 519 > /sys/class/gpio/export # JK
echo 520 > /sys/class/gpio/export # CLK

echo out > /sys/class/gpio/gpio487/direction
echo out > /sys/class/gpio/gpio488/direction

echo $1 > /sys/class/gpio/gpio487/value
echo 0 > /sys/class/gpio/gpio488/value
echo 1 > /sys/class/gpio/gpio488/value
